services:
  writer:
    extends:
      file: ./docker-compose.yml
      service: scanner
    command: ["python","-u","/app/writer_log.py"]
    restart: unless-stopped
    depends_on:
      scanner:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL","python -c \"import os,time,sys;p='/app/data/data.json';sys.exit(0 if (os.path.exists(p) and time.time()-os.path.getmtime(p)<60) else 1)\""]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s