services:
  scanner:
    build: .
    command: python -m app.service.scanner_p2p
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data

  dashboard:
    build: .
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file: .env
    volumes:
      - ./data:/app/data
